minimum_pre_commit_version: 2.20.0

# Temporarily exclude the following files from pre-commit checks. TODO: fix this
exclude: install_vs_code.sh$|install_oh_my_zsh_2.sh$

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: forbid-new-submodules
      # This is not available yet. See https://github.com/pre-commit/pre-commit-hooks/issues/835
      # - id: forbid-submodules
      - id: mixed-line-ending

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: shfmt
        args: [-bn, -ci, -l, -w, -i, "2"]

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.6.1
    hooks:
      - id: editorconfig-checker

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        #args: [--exclude-secrets, [regex]]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        #args: [-L, "word1,word2"]
