---
- name: Download Helm
  unarchive:
    src: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    remote_src: yes
    dest: /tmp

- name: Install Helm
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    owner: root
    mode: "755"
