---
- name: Add DBeaver GPG key
  apt_key: url=https://dbeaver.io/debs/dbeaver.gpg.key

- name: Add DBeaver APT repository
  apt_repository:
    repo: deb https://dbeaver.io/debs/dbeaver-ce /

- name: Install DBeaver
  apt:
    name: dbeaver-ce
