---
- name: Ensure Docker requirements are present
  apt: "name={{ docker_requirements }} state=present"

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: Ensure Docker required packages are present
  apt:
    name: "{{ docker_packages }}"

- name: Create docker group
  group:
    name: docker

- name: Add user to docker group
  user:
    append: yes
    name: "{{ lookup('env', 'USER') }}"
    groups:
      - docker
