- name: Install doctl
  community.general.snap:
    name: doctl

- name: Ensure we have doctl config directory
  file: path="{{ lookup('env', 'HOME') }}/.config/doctl" state=directory

- name: Add config
  template:
    src: config.yaml
    dest: "{{ lookup('env', 'HOME') }}/.config/doctl/config.yaml"
    owner: "{{ lookup('env', 'USER') }}"
    mode: "600"
