# Note. I couldn't make the man pages work. In the next Ubuntu Desktop LTS version exa can be installed as an `exa` package with `apt`.

- name: Create temporary directory for exa installation
  file:
    path: /tmp/exa
    state: directory

- name: Download and extract Exa
  unarchive:
    src: "https://github.com/ogham/exa/releases/download/v{{ exa_version }}/exa-linux-x86_64-v{{ exa_version }}.zip"
    dest: /tmp/exa
    remote_src: yes

- name: Install binary
  copy:
    src: /tmp/exa/bin/exa
    dest: /usr/local/bin/exa
    owner: root
    mode: "755"

- name: Install shell completion
  block:
  - name: Install completion for zsh
    copy:
      src: /tmp/exa/completions/exa.zsh
      dest: /usr/local/share/zsh/site-functions/_exa
      owner: root
      mode: "644"
    when: shell == "zsh"

  - name: Install completion for bash
    copy:
      src: /tmp/exa/completions/exa.bash
      dest: /etc/bash_completion.d/_exa
      owner: root
      mode: "644"
    when: shell == "bash"
