- name: Install kubectl
  get_url:
    url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    owner: root
    mode: "755"

- name: Configure editor
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/{{ shell_init_file }}"
    regexp: export KUBE_EDITOR="nano"
    line: export KUBE_EDITOR="nano"
