- include: packages/apt.yml
- include: packages/pip.yml
- include: packages/npm.yml

- include: terminator.yml
- include: kubectl.yml
- include: docker.yml
- include: go.yml
- include: nodejs.yml

- include: misc.yml
- include: python.yml
