- name: Download micro
  shell: curl https://getmic.ro | bash
  args:
    warn: no

- name: Install micro
  command: mv micro /usr/bin

# xclip is necessary for the clipboard to work properly
- name: Install xclip
  apt:
    name: xclip
