---
- name: Fix error popup on startup
  lineinfile:
    path: /etc/default/apport
    regexp: enabled=1
    line: enabled=0
  become: yes

- name: Add git config
  template:
    src: .gitconfig
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
    owner: "{{ lookup('env', 'USER') }}"
    mode: "600"
  when: full_name and email

- name: Set default editor
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/{{ shell_init_file }}"
    regexp: "export EDITOR={{ default_editor }}"
    line: "export EDITOR={{ default_editor }}"

- name: Remove unnecessary directories
  block:
    - name: Remove Documents directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/Documents"
        state: absent

    - name: Remove Music directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/Music"
        state: absent

    - name: Remove Public directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/Public"
        state: absent

    - name: Remove Templates directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/Templates"
        state: absent

    - name: Remove Videos directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/Videos"
        state: absent
