---
- name: Add git config
  template:
    src: .gitconfig
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
    owner: "{{ lookup('env', 'USER') }}"
    mode: "600"
  when: full_name and email

- name: Fix error popup on startup
  lineinfile:
    path: /etc/default/apport
    regexp: enabled=1
    line: enabled=0

- name: Set default editor
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/{{ shell_init_file }}"
    regexp: "export EDITOR={{ default_editor }}"
    line: "export EDITOR={{ default_editor }}"
