- name: Add git config
  template:
    src: .gitconfig
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
    owner: "{{ lookup('env', 'USER') }}"
    mode: "600"
  when: full_name and email

- name: Fix error popup on startup
  lineinfile:
    path: /etc/default/apport
    regexp: enabled=1
    line: enabled=0
