---
- name: Install ngrok
  unarchive:
    src: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
    remote_src: yes
    dest: /usr/local/bin
    owner: root
    mode: "755"

- name: Ensure we have ngrok config directory
  file: path="{{ lookup('env', 'HOME') }}/.ngrok2" state=directory

- name: Add ngrok config
  template:
    src: config.yaml
    dest: "{{ lookup('env', 'HOME') }}/.ngrok2/ngrok.yml"
    owner: "{{ lookup('env', 'USER') }}"
    mode: "600"
