---
- name: Add apt repository for latest Python version
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Install Python
  apt:
    name: "python{{ python_version }}"

- name: Install Python venv
  apt:
    name: "python{{ python_version }}-venv"
