- name: Check if yh has been installed already
  stat:
    path: /usr/local/bin/yh
  register: yh_file

- name: Install yh
  block:
    - name: Download yh
      unarchive:
        src: "https://github.com/andreazorzetto/yh/releases/download/v{{ yh_version }}/yh-linux-amd64.zip"
        remote_src: yes
        dest: /tmp

    - name: Install yh
      copy:
        src: /tmp/yh
        dest: /usr/local/bin/yh
        owner: root
        mode: "755"
  when: not yh_file.stat.exists
