- name: Check if yq has been installed already
  stat:
    path: /usr/local/bin/yq
  register: yq_file

- name: Install yq
  block:
    - name: Download yq
      unarchive:
        src: "https://github.com/mikefarah/yq/releases/download/v{{ yq_version }}/yq_linux_amd64.tar.gz"
        remote_src: yes
        dest: /tmp

    - name: Install yq
      copy:
        src: /tmp/yq_linux_amd64
        dest: /usr/local/bin/yq
        owner: root
        mode: "755"
  when: not yq_file.stat.exists
