apt_packages:
  - curl
  - unattended-upgrades  # Make sure we get security updates automatically
  - iftop  # For monitoring
  - mc
  - mysql-client
  - net-tools
  - locate
  - jq
  - python3-venv
  - pwgen
  - chromium-browser
  - ncdu

pip_packages:
  - tox
  - docker-compose
  - bpytop
  - thefuck

npm_packages:
  - yarn

docker_requirements:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

kubectl_version: 1.20.4
go_version: 1.16.2
python_version: 3.9
helm_version: 3.5.3
yq_version: 4.6.3

default_editor: nano
shell_init_file: .zshrc
