apt_packages:
  - curl
  - unattended-upgrades
  - iftop
  - mc
  - mysql-client
  - net-tools
  - locate
  - jq
  - python3-venv
  - pwgen
  - chromium-browser
  - ncdu
  - iotop
  - bat

pip_packages:
  - tox
  - docker-compose
  - bpytop
  - thefuck

npm_packages:
  - yarn

docker_requirements:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

kubectl_version: 1.20.4
go_version: 1.16.2
python_version: 3.9
helm_version: 3.5.3
yq_version: 4.6.3
exa_version: 0.10.1

default_editor: nano

# Only bash and zsh are supported
shell: bash
shell_init_file: "{{ '.zshrc' if shell == 'zsh' else '.bashrc' }}"
