---
apt_packages:
  - curl
  - unattended-upgrades
  - iftop
  - mc
  - mysql-client
  - net-tools
  - locate
  - jq
  - python3-venv
  - pwgen
  - chromium-browser
  - ncdu
  - iotop
  - bat
  - shellcheck
  - exa

pip_packages:
  - tox
  - docker-compose
  - bpytop
  - thefuck
  - poetry
  - tox-poetry

npm_packages:
  - yarn
  - fx
  - markdownlint-cli
  - prettier
  - markdown-link-check
  - json2yaml
  - "@vue/cli"

docker_requirements:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

nodejs_version: 18.x
kubectl_version: 1.20.4
go_version: 1.16.2
python_version: "3.10"
helm_version: 3.5.3
yq_version: 4.6.3
yh_version: 0.4.0
shfmt_version: 3.4.0
hadolint_version: 2.10.0

default_editor: nano

# Only bash and zsh are supported
shell: bash
shell_init_file: "{{ '.zshrc' if shell == 'zsh' else '.bashrc' }}"
