apt_packages:
  - curl
  - unattended-upgrades  # Make sure we get security updates automatically
  - htop  # For monitoring
  - iftop  # For monitoring
  - mc
  - mysql-client
  - net-tools
  - locate

pip_packages:
  - tox
  - docker-compose

npm_packages:
  - yarn

docker_requirements:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

kubectl_version: 1.20.4
go_version: 1.16.2
python_version: 3.9

default_editor: nano
shell_init_file: .zshrc
